//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AssetEntityWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AssetEntity), typeof(System.Object));
		L.RegFunction("AddListener", AddListener);
		L.RegFunction("RemoveListener", RemoveListener);
		L.RegFunction("SetAsset", SetAsset);
		L.RegFunction("OnLoaded", OnLoaded);
		L.RegFunction("GetInstantiate", GetInstantiate);
		L.RegFunction("New", _CreateAssetEntity);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("IsLoaded", get_IsLoaded, null);
		L.RegVar("assetType", get_assetType, null);
		L.RegVar("assetName", get_assetName, null);
		L.RegVar("hashCode", get_hashCode, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAssetEntity(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				string arg0 = ToLua.CheckString(L, 1);
				EAssetType arg1 = (EAssetType)ToLua.CheckObject(L, 2, typeof(EAssetType));
				AssetEntity obj = new AssetEntity(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: AssetEntity.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AssetEntity obj = (AssetEntity)ToLua.CheckObject<AssetEntity>(L, 1);
			DAssetsCallback arg0 = (DAssetsCallback)ToLua.CheckDelegate<DAssetsCallback>(L, 2);
			obj.AddListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AssetEntity obj = (AssetEntity)ToLua.CheckObject<AssetEntity>(L, 1);
			DAssetsCallback arg0 = (DAssetsCallback)ToLua.CheckDelegate<DAssetsCallback>(L, 2);
			obj.RemoveListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAsset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AssetEntity obj = (AssetEntity)ToLua.CheckObject<AssetEntity>(L, 1);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.CheckObject<UnityEngine.Object>(L, 2);
			obj.SetAsset(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnLoaded(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AssetEntity obj = (AssetEntity)ToLua.CheckObject<AssetEntity>(L, 1);
			obj.OnLoaded();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInstantiate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AssetEntity obj = (AssetEntity)ToLua.CheckObject<AssetEntity>(L, 1);
			UnityEngine.Object o = obj.GetInstantiate();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsLoaded(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AssetEntity obj = (AssetEntity)o;
			bool ret = obj.IsLoaded;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsLoaded on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_assetType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AssetEntity obj = (AssetEntity)o;
			EAssetType ret = obj.assetType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index assetType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_assetName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AssetEntity obj = (AssetEntity)o;
			string ret = obj.assetName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index assetName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hashCode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AssetEntity obj = (AssetEntity)o;
			int ret = obj.hashCode;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index hashCode on a nil value");
		}
	}
}

